# Configuration for request-info - https://github.com/behaviorbot/request-info

# Warn about insufficient information on these events type
requestInfoOn:
  pullRequest: true
  issue: true

# Comment to reply with
requestInfoReplyComment: >
  Hey there! You didn't give us a whole lot of info about this issue. We would love if you could provide more details about what you're trying to accomplish here. 

# Label to be added to Issues and Pull Requests with insufficient information given
requestInfoLabelToAdd: needs-more-info

# Require Issues to contain more information than what is provided in the issue templates
checkIssueTemplate: true

# Require Pull Requests to contain more information than what is provided in the PR template
checkPullRequestTemplate: true
