# Configuration for request-info - https://github.com/behaviorbot/request-info

requestInfoOn:
  pullRequest: true
  issue: true

requestInfoReplyComment: >
  Hey there! You didn't give us a whole lot of info about this issue. We would love if you could provide more details about what you're trying to accomplish here. 

requestInfoLabelToAdd: needs-more-info

checkIssueTemplate: true
checkPullRequestTemplate: true
