# This is the complex Travis configuration, 
# which is intended for use on open source libraries 
# which need compatibility over many platforms

# Base distribution:
dist: bionic

# Use new container infrastructure to enable caching
sudo: true

# We set the compiler values here to tell Travis 
# to use a different compiler per set of arguments.
matrix:
  include:
  # The LaTeX builds on Linux.
  - language: generic
    env: CTEX="pdfLaTeX"
    compiler: ": pdfLaTeX"

  - language: generic
    env: CTEX="LuaLaTeX"
    compiler: ": LuaLaTeX"
    addons: {apt: {packages: [texlive-luatex]}}

  - language: generic
    env: CTEX="XeLaTeX"
    compiler: ": XeLaTeX"
    addons: {apt: {packages: [texlive-xetex]}}
    
  # The LaTeX builds on Windows.
  - language: shell
    env: CTEX="pdfLaTeX" TEXREP="C:\temp\miktex" TEXPATH="/c/temp/miktex/miktex/bin/x64"
    compiler: ": pdfLaTeX"
    os: windows

  - language: shell
    env: CTEX="LuaLaTeX" TEXREP="C:\temp\miktex" TEXPATH="/c/temp/miktex/miktex/bin/x64"
    compiler: ": LuaLaTeX"
    os: windows

  - language: shell
    env: CTEX="XeLaTeX" TEXREP="C:\temp\miktex" TEXPATH="/c/temp/miktex/miktex/bin/x64"
    compiler: ": XeLaTeX"
    os: windows

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC
# Clear possible LaTeX auxiliary files
- ./clear.sh
# Update software repositiories
- echo "$OSTYPE"
- |
  case "$OSTYPE"
    linux) 
      sudo apt-get update
      ;;
    msys) 
      curl -L https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/miktexsetup-2.9.6942-x64.zip > miktexsetup.zip
      unzip miktexsetup.zip
      ;;
  esac 

install:
- |
  case "$OS" in
    linux) 
      sudo apt-get install -y texlive texlive-bibtex-extra texlive-fonts-extra texlive-latex-extra texlive-lang-polish tex-gyre
      ;;
    msys)
      miktexsetup.exe --verbose --local-package-repository="$TEXREP" --package-set=basic download
      miktexsetup.exe --verbose --local-package-repository="$TEXREP" --package-set=basic install
      export PATH="$TEXPATH:$PATH"
      ;;
  esac

script:
- |
  case "$CTEX" in
    pdfLaTeX)
      ./pdftex-build.sh
      ;;
    LuaLaTeX)
      ./luatex-build.sh
      ;;
    XeLaTeX)
      ./xetex-build.sh
      ;;
  esac

# Do not send email notifications after every build. 
notifications:
  email: false
