image: Visual Studio 2019

build: off

before_test:
- set PATH=C:\temp\miktex\miktex\bin\x64;C:\Program Files\Git\mingw64\bin;%PATH%
- Invoke-WebRequest "https://miktex.org/download/win/miktexsetup-x64.zip" -OutFile "miktexsetup-x64.zip"
- 7z x miktexsetup*
- miktexsetup --verbose --local-package-repository=C:\temp\miktex --package-set=basic download
- miktexsetup --quiet --local-package-repository=C:\temp\miktex --package-set=basic install

# clone_folder: "c:\\stack"
environment:
  matrix:
  - BUILD: "pdfLaTeX"
  - BUILD: "LuaLaTeX"
  - BUILD: "XeLaTeX"

test_script:
- |
  case "$BUILD" in
    pdfLaTeX)
      ./pdftex-build.sh
      ;;
    LuaLaTeX)
      ./luatex-build.sh
      ;;
    XeLaTeX)
      ./xetex-build.sh
      ;;
  esac

