name: CI

on:
  push:
  pull_request:

jobs:

  scons:
    strategy:
      matrix:
        tex-compiler: [lua, pdf]
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y   \
               biber                \
               latexmk              \
               poppler-utils        \
               scons                \
               texlive              \
               texlive-bibtex-extra \
               texlive-fonts-extra  \
               texlive-latex-extra  \
               texlive-lang-polish  \
               texlive-luatex       \
               texlive-xetex        \
               tex-gyre

      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Generate PDF file
        run: scons ${{ matrix.tex-compiler }}

      - name: Verify build with referential text
        run: scons verify-build
