name: CI

on:
  push:
  pull_request:

jobs:
  
  make:
    strategy:
      matrix:
        tex-compiler: [lua, pdf, xetex]
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y   \
               biber                \
               latexmk              \
               poppler-utils        \
               texlive              \
               texlive-bibtex-extra \
               texlive-fonts-extra  \
               texlive-latex-extra  \
               texlive-lang-polish  \
               texlive-luatex       \
               texlive-xetex        \
               tex-gyre
      
      - name: Checkout git repository
        uses: actions/checkout@v2
      
      - name: Generate PDF file
        run: make ${{ matrix.tex-compiler }}
      
      - name: Verify build with referential text
        run: ./scripts/verify-build.sh ${{ matrix.tex-compiler }} 
