name: CI

on:
  push:
  pull_request:

jobs:
  
  make:
    strategy:
      matrix:
        tex-compiler: [lua, pdf, xetex]
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get install -y   \
               biber                \
               latexmk              \
               poppler-utils        \
               texlive              \
               texlive-bibtex-extra \
               texlive-fonts-extra  \
               texlive-latex-extra  \
               texlive-lang-polish  \
               texlive-luatex       \
               texlive-xetex        \
               tex-gyre
      - uses: actions/checkout@v2
      - run: make ${{ matrix.tex-compiler }}
      - run: ./scripts/verify-build.sh ${{ matrix.tex-compiler }} 
